### PR TITLE
Ua 47 max data charts

### PR DESCRIPTION
**Pull request by lampvux**
Recursive load all data until it reached its limit using Max range button.

### CODE REVIEW

**Comment by pixelomo** [comment]
The chart breaks on Indices when I click Max and then 1M afterwards
Screenshot 2022-03-22 at 10 09 30

Forex and Stocks max range does not zoom out to show full range, zoom should be different for each category:
Stocks: 18 Years
Forex: 12 Years
Cryptocurrency: 8 Years
Indices: 10 Years

**Comment by pixelomo** [comment]
Thanks @9kmmr I can see the max option is working better with this update, the zoom still needs to change depending on the category. For example when I click max on forex I see this
Screenshot 2022-03-22 at 16 25 51

Could we change the forex zoom level so we can see all graph data back to 2010 like this please?
Screenshot 2022-03-22 at 16 24 41

Could you also do this for stocks to 2004 (18 years), crypto to 2014 (8 years) and indices to 2012 (10 years)

Indices zoom out now when clicking max but behaviour is a little strange, every second it zooms out further all the way to 1973
https://user-images.githubusercontent.com/4670058/159429638-ef44ead5-d967-48f8-b7de-4ad876401a18.mov

**Comment by pixelomo** [comment]
When I click Max in Nasdaq I see this endpoint request
`https://api.finage.co.uk/agg/index/IXIC/1week/1947-04-11/1962-04-07?limit=3000&apikey=API_KEYTS5Q5H4EBFHIHT4WK6KB583OZ2HS8ZJJ&sort=asc`

Similar for DJI
`https://api.finage.co.uk/agg/index/DJI/1week/1962-04-07/1977-04-03?limit=3000&apikey=API_KEYTS5Q5H4EBFHIHT4WK6KB583OZ2HS8ZJJ&sort=asc`

TSLA
`https://api.finage.co.uk/agg/stock/TSLA/1/week/1992-03-30/2007-03-27?limit=3000&apikey=API_KEYTS5Q5H4EBFHIHT4WK6KB583OZ2HS8ZJJ&sort=desc`

It seems the range selector logic for generating dates is not working as expected.

On Nasdaq I still see the max zoom delay
https://user-images.githubusercontent.com/4670058/159429638-ef44ead5-d967-48f8-b7de-4ad876401a18.mov

**Comment by lampvux** [comment]
> When I click Max in Nasdaq I see this endpoint request `https://api.finage.co.uk/agg/index/IXIC/1week/1947-04-11/1962-04-07?limit=3000&apikey=API_KEYTS5Q5H4EBFHIHT4WK6KB583OZ2HS8ZJJ&sort=asc`
> 
> Similar for DJI `https://api.finage.co.uk/agg/index/DJI/1week/1962-04-07/1977-04-03?limit=3000&apikey=API_KEYTS5Q5H4EBFHIHT4WK6KB583OZ2HS8ZJJ&sort=asc`
> 
> TSLA `https://api.finage.co.uk/agg/stock/TSLA/1/week/1992-03-30/2007-03-27?limit=3000&apikey=API_KEYTS5Q5H4EBFHIHT4WK6KB583OZ2HS8ZJJ&sort=desc`
> 
> It seems the range selector logic for generating dates is not working as expected.
> 

It is a recursive function to load all data until it reached api's limit, So that It will continue load until no data returned.

> On Nasdaq I still see the max zoom delay

I reduced the delay in the latest commit. But It will not display data instantly when click the button.

**Pull request merged**
