### PR TITLE
add a search coin cf, add coins list store, remove storing in localst…

### PR DESCRIPTION
**Pull request by lampvux**
1. add search coin cloud function, searching for not existed coin in top coins.
2. moving store coin lists to nuxtjs store, remove storing coins in localStorage.
3. remove duplicate find in _symbol.js

### CODE REVIEW

**Comment by lampvux** [comment]
I have deployed the cloud function but the rewrite rule change to access the new cloud function need to re-deploy the hosting I think.
Cloud be deploy the current hosting with new firebase.json rules and current source code without this changes first.

**Comment by lampvux** [comment]
**Updated**

I have Updated the rewrite rule with new cloud function. 
The cloud function for searching new cryptocurrency symbol from CoinMarketCap is working properly.

But some symbols maybe not display properly because both Binance & Finage do not have any historical data of them.
It's maybe the problem from Finage because we get it from their top 200 but they do not have historical data somehow.

**PS**
We can use CMC to fetch unavailable crypto on both Binance & Finage but the current plan for CMC pro is not supported historical data.

**More Update**
I've checked out the coingecko API, and it could be used for free with the limit 50 calls/minute for historical ohlcv of symbols are not found in both Finace & Binace.

**Review by pixelomo — CHANGES_REQUESTED** [review]
After running the following in /frontend
`npm run-script generate`
`firebase emulators:start`

I see this warning in the terminal:
```
 functions: The following emulators are not running, calls to these services from the Functions emulator will affect production: auth, firestore, database, pubsub, storage
⚠  Your requested "node" version "16" doesn't match your global version "12"
i  hosting: Serving hosting files from: dist
✔  hosting: Local server: http://localhost:5000
⚠  ui: Emulator UI unable to start on port 4000, starting on 4001 instead.
i  ui: Emulator UI logging to ui-debug.log
i  functions: Watching "/Users/alan/Documents/Web/the-markets/frontend/functions" for Cloud Functions...
⚠  /Users/alan/Documents/Web/the-markets/frontend/functions/index.js:33
    const coin = await searchCoin(req.query.slug??"");
                                                 ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1052:16)
    at Module._compile (internal/modules/cjs/loader.js:1100:27)
    at Module._compile (pkg/prelude/bootstrap.js:1394:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1338:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at initializeRuntime (/Users/alan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:640:29)
```
the app does run but the nvm warning and the bug in functions.js should be resolved:


Many of the new item pages are not loading, it seems to be more common with coins with multiple word names such as http://localhost:5000/cryptocurrency/magic-internet-money 

console error
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:5000/api/search?slug=magic-internet-money
```

Many of the prices on crypto are not fixed to 2 decimal places anymore

Also the infinite loader seems to have broken,

**Comment by lampvux** [comment]
`Your requested "node" version "16" doesn't match your global version "12"` 
This is the cause of your local error, you are using node 12 but the **??** (Nullish coalescing operator) only available from node version >= v14.
It will not affect to production because I've already set the runtime in [firebase.json](https://github.com/Urala-Communications/the-markets/blob/e7016f7b38ecd1ece93a37f409696c54048be745/frontend/firebase.json#L37) to nodejs16. 
Upgrade your local node version to 14. will fix the issue.
    
    functions: The following emulators are not running, calls to these services from the Functions emulator will affect 
    production: auth, firestore, database, pubsub, storage
    ⚠  Your requested "node" version "16" doesn't match your global version "12"
    i  hosting: Serving hosting files from: dist
    ✔  hosting: Local server: http://localhost:5000
    ⚠  ui: Emulator UI unable to start on port 4000, starting on 4001 instead.
    i  ui: Emulator UI logging to ui-debug.log
    i  functions: Watching "/Users/alan/Documents/Web/the-markets/frontend/functions" for Cloud Functions...
    ⚠  /Users/alan/Documents/Web/the-markets/frontend/functions/index.js:33
        const coin = await searchCoin(req.query.slug??"");
                                                 ^

    SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1052:16)
    at Module._compile (internal/modules/cjs/loader.js:1100:27)
    at Module._compile (pkg/prelude/bootstrap.js:1394:32)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module.require (pkg/prelude/bootstrap.js:1338:31)
    at require (internal/modules/cjs/helpers.js:72:18)
    at initializeRuntime (/Users/alan/.cache/firebase/tools/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js:640:29)
    
Fix this local issue with my latest commit will make both UA-48 and UA-46 work when displaying a not-listed crypto symbol.

**Note***

Because of security reason, I've set these lines to the cloud function [line 8](https://github.com/Urala-Communications/the-markets/blob/e7016f7b38ecd1ece93a37f409696c54048be745/frontend/functions/index.js#L8) and [line 25](https://github.com/Urala-Communications/the-markets/blob/e7016f7b38ecd1ece93a37f409696c54048be745/frontend/functions/index.js#L25) :

    res.set('Access-Control-Allow-Origin', process.env.SITE_URL);
    
 In testing purpose you should change to this before running **firebase emulators:start**: 

    res.set('Access-Control-Allow-Origin', "*");

**Comment by pixelomo** [comment]
Thanks for your help, I changed my local version to 16 but firebase continued saying it was 12, it required re-installing firebase to read the new version. The emulator now starts up without errors. I have also changed lines 8 and 25 of the functions to
`res.set('Access-Control-Allow-Origin', "*");`

When the crypto page loads I see this terminal error
```
functions: Beginning execution of "coins"
>  Error: Request failed with status code 401
...
url: 'https://api.finage.co.uk/list/cryptocurrency?apikey=undefined&limit=200',
...
functions: TypeError: Cannot read properties of undefined (reading 'length')
at /Users/alan/Documents/Web/the-markets/frontend/functions/index.js
```

it seems the api key is undefined

**Pull request merged**
